[project]
name = "data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "duckdb>=1.5.1",
  "fastapi>=0.135.3",
  "pydantic-settings>=2.9.1",
  "sf-hamilton[visualization]>=1.89.0",
  "uvicorn[standard]>=0.42.0",
]

[project.scripts]
dev = "uvicorn main:app --reload --port 8000"

[dependency-groups]
dev = ["ruff>=0.12.2", "ty>=0.0.1a13"]

[tool.ruff]
target-version = "py313"
line-length = 120

[tool.ruff.lint]
select = [
  "E", # pycodestyle errors
  "W", # pycodestyle warnings
  "F", # pyflakes
  "I", # isort
  "N", # pep8-naming
  "UP", # pyupgrade
  "B", # flake8-bugbear
  "SIM", # flake8-simplify
  "TCH", # flake8-type-checking
]

[tool.ty.environment]
python-version = "3.13"
