// Generates public/sprite.svg + src/lib/icon-names.ts from lucide-static.
// Add a name to ICONS, then: node scripts/generate-sprite.mjs
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ICONS = [
  "activity",
  "archive",
  "archive-restore",
  "arrow-left",
  "ban",
  "calendar",
  "chart-no-axes-column",
  "check",
  "check-check",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "circle-dashed",
  "circle-dot-dashed",
  "circle-user",
  "clipboard-pen",
  "columns-2",
  "copy",
  "corner-down-right",
  "database",
  "diamond",
  "door-closed",
  "download",
  "eraser",
  "file-text",
  "files",
  "funnel",
  "grip-vertical",
  "layers",
  "layout-dashboard",
  "layout-grid",
  "loader-circle",
  "log-out",
  "mail",
  "map",
  "megaphone",
  "menu",
  "minus",
  "more-horizontal",
  "paintbrush",
  "panel-left-close",
  "panel-left-open",
  "panel-right-close",
  "panel-right-open",
  "pencil",
  "phone",
  "plus",
  "qr-code",
  "radio",
  "rows-3",
  "scissors",
  "search",
  "send",
  "settings",
  "settings-2",
  "sparkles",
  "sun",
  "tag",
  "trash-2",
  "trending-up",
  "triangle-alert",
  "upload",
  "user-round",
  "user-round-plus",
  "users",
  "users-round",
  "waypoints",
  "x",
];

const here = dirname(fileURLToPath(import.meta.url));
// pnpm may hoist lucide-static to the workspace root.
const candidates = [
  resolve(here, "../node_modules/lucide-static/icons"),
  resolve(here, "../../../node_modules/lucide-static/icons"),
];
const iconsDir = candidates.find((d) => existsSync(d));
if (!iconsDir) throw new Error("lucide-static not found; pnpm install first");

const symbols = ICONS.toSorted().map((name) => {
  const svg = readFileSync(join(iconsDir, `${name}.svg`), "utf8");
  const inner = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/)?.[1].trim();
  if (!inner) throw new Error(`could not parse ${name}.svg`);
  return `<symbol id="${name}" viewBox="0 0 24 24">${inner.replaceAll(/\s+/g, " ")}</symbol>`;
});

const outDir = resolve(here, "../public");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, "sprite.svg"),
  `<svg xmlns="http://www.w3.org/2000/svg"><defs>${symbols.join("")}</defs></svg>\n`,
);
writeFileSync(
  resolve(here, "../src/lib/icon-names.ts"),
  `// Generated by scripts/generate-sprite.mjs — do not edit.
export const ICON_NAMES = ${JSON.stringify(ICONS.toSorted(), null, 2)} as const;
export type IconName = (typeof ICON_NAMES)[number];
`,
);
console.log(`sprite.svg: ${ICONS.length} icons`);
