import type { SVGProps } from "react";
import type { IconName } from "~/lib/icon-names";

// Sprite-backed icon: symbols live in /sprite.svg (generated by
// scripts/generate-sprite.mjs). Size/stroke utilities on the svg
// inherit into the symbol, matching lucide-react's styling contract.
export function Icon({ name, ...props }: { name: IconName } & SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={24}
      height={24}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={2}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
      {...props}
    >
      <use href={`/sprite.svg#${name}`} />
    </svg>
  );
}
