/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Geist_400Regular"],
        "sans-bold": ["Geist_700Bold"],
        mono: ["Geist_400Regular"],
      },
      colors: {
        background: "#f6f6f6",
        "background-dark": "#0a0a0a",
        surface: "#ffffff",
        "surface-dark": "#1b1b1b",
        foreground: "#1b1b1b",
        "foreground-dark": "#ededed",
        primary: "#1b1b1b",
        "primary-foreground": "#fcfcfc",
        "primary-dark": "#ededed",
        "primary-foreground-dark": "#1b1b1b",
        badge: "#DEDEDE",
        "badge-dark": "#333333",
        muted: "#fcfcfc",
        "muted-foreground": "#888888",
        "muted-dark": "#141414",
        "muted-foreground-dark": "#a3a3a3",
        faded: "#f8f8f8",
        "faded-dark": "#101010",
        border: "#e5e5e5",
        "border-dark": "#333333",
        destructive: "#D82000",
        "destructive-dark": "#f9524c",
      },
    },
  },
  plugins: [],
};
