/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Geist_400Regular"],
        "sans-bold": ["Geist_700Bold"],
        mono: ["Geist_400Regular"],
      },
      colors: {
        background: "#fcfcfc",
        "background-dark": "#0a0a0a",
        surface: "#ffffff",
        "surface-dark": "#1b1b1b",
        foreground: "#1b1b1b",
        "foreground-dark": "#ededed",
        primary: "#1b1b1b",
        "primary-foreground": "#fcfcfc",
        "primary-dark": "#ededed",
        "primary-foreground-dark": "#1b1b1b",
        badge: "#DEDEDE",
        "badge-dark": "#333333",
        muted: "#f5f5f5",
        "muted-foreground": "#888888",
        "muted-dark": "#333333",
        "muted-foreground-dark": "#a3a3a3",
        border: "#e5e5e5",
        "border-dark": "#333333",
        "blue-light": "#B7E3F2",
        "blue-light-dark": "#1A3A45",
        "blue-dark": "#3D7385",
        "blue-dark-dark": "#7ECDE0",
        "red-light": "#FFCAC1",
        "red-dark": "#D82000",
        "yellow-light": "#FFCE9E",
        "yellow-dark": "#AD4500",
        "green-light": "#C4EDB5",
        "green-dark": "#447134",
      },
    },
  },
  plugins: [],
};
