import { sql } from "drizzle-orm";
import { integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { campaigns } from "./campaigns";
import { scripts } from "./scripts";
import { users } from "./auth/users";

// Published turf — a forever snapshot. Generated by the cutter's
// publish flow and never modified afterward (the only "dynamic"
// reference is `scriptId`, since script content can evolve). The
// payload (buildings → doors → persons) lives in `turf_data` and
// is fetched on demand.
//
// `zoneId` and `segmentId` are stored as plain uuids (no FK) so
// admins can delete or reorganize the source zone/segment without
// breaking historical turfs. Stale-tracking based on whether the
// referenced row still exists is a follow-up.
//
// `status` gates the canvasser-facing lifecycle: only `'active'`
// turfs honor their `turfCode` (the partial unique index enforces
// uniqueness only across active turfs, so archived turfs hold
// expired codes harmlessly without blocking new turfs from
// reusing them).
export type TurfStatus = "active" | "archived";

export const turfs = pgTable(
  "turfs",
  {
    turfId: uuid().defaultRandom().primaryKey(),
    campaignId: uuid()
      .notNull()
      .references(() => campaigns.campaignId),
    segmentId: uuid().notNull(),
    // Source zone (the cutter scope) and its parent group. Both kept
    // as plain values rather than FKs — see comment above.
    zoneId: uuid().notNull(),
    zoneGroupId: uuid().notNull(),
    scriptId: uuid()
      .notNull()
      .references(() => scripts.scriptId),
    name: text().notNull(),
    turfCode: text(),
    status: text().$type<TurfStatus>().notNull().default("active"),
    geometry: jsonb().$type<GeoJsonPolygon>(),
    doorCount: integer(),
    personCount: integer(),
    createdBy: uuid()
      .notNull()
      .references(() => users.id),
    createdAt: timestamp({ withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex("turfs_active_turf_code")
      .on(t.turfCode)
      .where(sql`${t.status} = 'active'`),
  ],
);

export type GeoJsonPolygon = {
  type: "Polygon";
  coordinates: number[][][];
};
