import { sql } from "drizzle-orm";
import { integer, jsonb, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { app } from "./app";
import { campaigns } from "./campaigns";
import { datasetVersions } from "./datasets";
import { scripts } from "./scripts";
import { segments } from "./segments";
import { users } from "./auth/users";
import { zoneGroups } from "./zone-groups";

// Published turf — a forever snapshot. Generated by the cutter's
// publish flow and never modified afterward. `scriptId` and
// `segmentId` are dynamic references (their content can evolve; the
// `criteria` stamp carries the publish-time recipe). The payload
// (buildings → doors → persons) lives in `turf_data` and is fetched
// on demand.
//
// `segmentId` and `zoneGroupId` are real FKs: segments and zone
// groups archive instead of deleting, so the rows a turf references
// exist forever. `zoneId` alone stays a plain uuid — zones are
// working state (cleared, redrawn, deleted) — so the zone's identity
// is stamped at publish instead: `zoneName` for labels and `zoneKeys`
// for geography (with the key group from the zoneGroupId join — key
// groups are immutable — the boundary service resolves keys to
// polygons), the same pattern as `criteria`.
//
// `zoneId` and `zoneGroupId` are nullable: turfs cut on a campaign
// without a zone group hang off the campaign's segment directly.
//
// `status` gates the canvasser-facing lifecycle: only `'active'`
// turfs honor their `turfCode` (the partial unique index enforces
// uniqueness only across active turfs, so archived turfs hold
// expired codes harmlessly without blocking new turfs from
// reusing them).
export type TurfStatus = "active" | "archived";

export const turfs = app.table(
  "turfs",
  {
    turfId: uuid().defaultRandom().primaryKey(),
    campaignId: uuid()
      .notNull()
      .references(() => campaigns.campaignId),
    segmentId: uuid()
      .notNull()
      .references(() => segments.segmentId),
    // The dataset version this turf was cut against — stamped here at publish
    // time (not derived through the segment, which stores no version), so the
    // historical record stays accurate across dataset updates. Dataset
    // versions are immutable and retained forever, so the FK enforces that
    // a version a turf references can't be deleted. Nullable until set at
    // publish.
    datasetVersionId: uuid().references(() => datasetVersions.datasetVersionId),
    // Source zone (the cutter scope) and its parent group — see the
    // FK-vs-stamp note above. Null when the campaign has no zone group
    // (cut against the full segment).
    zoneId: uuid(),
    zoneGroupId: uuid().references(() => zoneGroups.zoneGroupId),
    // The zone as it was at publish time. Zones are mutable working
    // state, so these stamps are what keep by-zone grouping, labels,
    // and map rendering stable after a zone is renamed, redrawn, or
    // deleted. All null on zoneless turfs and on turfs published
    // before the columns existed.
    zoneName: text(),
    zoneKeys: jsonb().$type<string[]>(),
    scriptId: uuid()
      .notNull()
      .references(() => scripts.scriptId),
    name: text().notNull(),
    turfCode: text(),
    // The segment criteria as they were at publish time. `segmentId` is a
    // live reference to an editable row, so this snapshot is the only
    // durable record of the recipe that produced the turf's membership.
    // Null on turfs published before the column existed.
    criteria: jsonb(),
    status: text().$type<TurfStatus>().notNull().default("active"),
    geometry: jsonb().$type<GeoJsonPolygon>(),
    // [lng, lat] per building — slim publish-time projection so map
    // reads never detoast the full turf_data payload.
    buildingCoords: jsonb().$type<[number, number][]>(),
    doorCount: integer(),
    personCount: integer(),
    createdBy: uuid()
      .notNull()
      .references(() => users.id),
    createdAt: timestamp({ withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex("turfs_active_turf_code")
      .on(t.turfCode)
      .where(sql`${t.status} = 'active'`),
  ],
);

export type GeoJsonPolygon = {
  type: "Polygon";
  coordinates: number[][][];
};
