// Generated by scripts/generate-sprite.mjs — do not edit.
export const ICON_NAMES = [
  "check",
  "check-check",
  "chevron-down",
  "copy",
  "door-closed",
  "layout-grid",
  "loader-circle",
  "map",
  "megaphone",
  "phone",
  "qr-code",
  "radio",
  "rows-3",
  "user-round",
  "users-round",
  "waypoints",
] as const;
export type IconName = (typeof ICON_NAMES)[number];
